# Generated by Django 4.0.5 on 2022-07-03 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_contact_subscriberemail_alter_blog_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
